### POST user
POST http://localhost:3000/user
Content-Type: application/json

{
  "username": "oleg11",
  "email": "oleg@oleg12.com",
  "password": "Password123",
  "gender": "male"
}

### GET all users request
GET http://localhost:3000/user

###
GET http://localhost:3000
